name: Smoke Tests - PR

on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
    # clonar o projeto na maquina
      - name: Clonar o projeto
        uses: actions/checkout@v3

    # instalar o java
      - name: Instalar Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

    # instalar o chrome
    - name: Instalar o chrome
      uses: browser-actions/setup-chrome@v1
      #run: |
        #wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        #sudo apt install ./google-chrome-stable_current_amd64.deb
        #run: chrome --version

    # instalar o chrome driver (para windows)
    - name: Instalar chrome driver
      uses: nanasess/setup-chromedriver@v2
      run: chromedriver --url-base=/wd/hub &

    # executar os testes
    - name: Executar Testes (Run Test)
      run: mvn test -Dtest=RunCucumberTest -Dbrowser=chrome-ci

    # gerar relatorio